platform :ios, '13.0'
use_modular_headers!
use_frameworks!

target 'RxNetworkService_Example' do
  pod 'RxNetworkService', :path => '../'
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SWXMLHash', '~> 6.0.0'
  
  target 'RxNetworkService_Tests' do
    inherit! :search_paths

    
  end
end
