platform :ios, '13.0'
use_modular_headers!
use_frameworks!

target 'RxNetworkService_Example' do
  pod 'RxNetworkService', :path => '../'
  
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'SWXMLHash', '6.0.0'
  
  target 'RxNetworkService_Tests' do
    inherit! :search_paths

    
  end
end
